name: sync-22.05
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: ustcmirror/rsync:latest
          options: -v ${{ github.workspace }}/repo/22.05:/data -e RSYNC_HOST=rsync://mirror.pkgbuild.com/ -e RSYNC_PATH=packages
          run: "entry.sh"
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './repo/22.05'
          production-branch: master
          github-token: ${{ secrets.TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
